apiVersion: apps/v1
kind: Deployment
metadata:
  name: fabric-rest-api
  namespace: org1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fabric-rest-api
  template:
    metadata:
      labels:
        app: fabric-rest-api
    spec:
      containers:
      - name: api
        image: node:18
        workingDir: /app
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: config
          mountPath: /app/config
        - name: wallet
          mountPath: /app/wallet
        env:
        - name: CHANNEL_NAME
          value: "channel"
        - name: CHAINCODE_NAME
          value: "cc-go"
        - name: ORG_MSPID
          value: "Org1MSP"
        - name: PEER_ENDPOINT
          value: "peer1-org1.localho.st:443"
      volumes:
      - name: config
        configMap:
          name: hlf-config
      - name: wallet
        secret:
          secretName: org1-admin-credentials

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hlf-config
  namespace: org1
data:
  connection.json: |
    {
      "name": "test-network",
      "version": "1.0",
      "client": {
        "organization": "Org1",
        "connection": {
          "timeout": {
            "peer": {
              "endorser": "300"
            }
          }
        }
      },
      "organizations": {
        "Org1": {
          "mspid": "Org1MSP",
          "peers": ["peer1-org1.localho.st"],
          "certificateAuthorities": ["org1-ca.localho.st"]
        }
      },
      "peers": {
        "peer1-org1.localho.st": {
          "url": "grpcs://peer1-org1.localho.st:443",
          "tlsCACerts": {
            "pem": "-----BEGIN CERTIFICATE-----..." # Replace with actual CA cert
          }
        }
      }
    }

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: fabric-rest-api
  namespace: org1
spec:
  hosts:
  - "api.localho.st"
  gateways:
  - istio-system/istio-gateway
  http:
  - route:
    - destination:
        host: fabric-rest-api
        port:
          number: 3000